### PR TITLE
Issue #19: change search pin color to gray

### LINKED ISSUE #19: Mapbox search: Change search pin color
The color of the search results pin is almost exactly the same as the color of the polling locations.

Ideal solution:
Change search pin color to a medium gray like #bababa

Fine solution:
Leave search pin color as-is and change polling location results color to the gray #bababa

### PR DESCRIPTION
**Pull request by elizzard**

### CODE REVIEW

**Comment by elizzard** [comment]
This will make a small merge conflict with #17, but it's really straightforward to resolve.

**Comment by ajlevitz** [comment]
Could you attach a screenshot of this? The code seems like it'd be fine but I can only actually verify through the screenshot :-P

**Comment by elizzard** [comment]
Resolved conflict, and screenshot:
Screen Shot 2020-10-28 at 10 56 52 PM

**Review by ajlevitz — APPROVED** [review]

**Comment by rmx90210** [comment]
@elizzard sorry about that conflict, I did something silly and did an `--amend` commit on `master`. I hope it wasn't too gnarly 🤦

**Comment by elizzard** [comment]
@rbrtmrtn What conflict? I don't see anything :p
Tbh I expected it, since I literally edited the same line in two PRs. So no worries.
What kind of merge should I use? And should I merge or would you prefer to?

**Comment by rmx90210** [comment]
image

I was trying to get to Phoenix and accidentally landed here at the airport. This might be edge case-y but I feel like maybe the color could use some more contrast?

For example here's `#505050`:

image

**Comment by elizzard** [comment]
@rbrtmrtn I agree, I was wondering about making it darker as well.  Even compared to grey patches on my screenshots it would look better/contrast-ier. 
@ajlevitz  thoughts?

**Comment by ajlevitz** [comment]
Darker does seem good!! Nice catch, y'all

**Comment by rmx90210** [comment]
I think we were racing @elizzard 😂  I'll go ahead and merge. Thank you!

**Comment by rmx90210** [comment]
Deploying to prod

**Pull request merged**
